name: "mooncakes"
mode: "dev"
version: "v0.0.0"
port: 8084
start_time: "2021-10-06"
machine_id: 1

auth:
  jwt_expire: 8720

log:
  level: "debug"
  filename: "mooncakes.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "10.88.0.2"
  port: 3306
  user: "root"
  password: "chenyuhan123000"
  dbname: "mooncakes"
  max_open_conns: 200
  max_idle_conns: 50
